In [2]:
import numpy as np


In [3]:
import pandas as pd

In [4]:
age = np.random.randint(18,95, 100)
salary = np.random.randint(2000,20000,100)



In [5]:
df = pd.DataFrame({'Age': age, 'Salary': salary})
df

Age  Salary
0    76   19322
1    46   11758
2    87    6073
3    77   10697
4    20    6701
..  ...     ...
95   57   16324
96   18   15577
97   46   11457
98   83   10508
99   70    8827

[100 rows x 2 columns]

In [6]:
df['Purchased'] = df['Age']
df

Age  Salary  Purchased
0    76   19322         76
1    46   11758         46
2    87    6073         87
3    77   10697         77
4    20    6701         20
..  ...     ...        ...
95   57   16324         57
96   18   15577         18
97   46   11457         46
98   83   10508         83
99   70    8827         70

[100 rows x 3 columns]

In [7]:
df['Purchased'] = df.apply(lambda x: 1 if (6*x['Age']+3*x['Salary']>38000) else 0, axis = 1)
df


Age  Salary  Purchased
0    76   19322          1
1    46   11758          0
2    87    6073          0
3    77   10697          0
4    20    6701          0
..  ...     ...        ...
95   57   16324          1
96   18   15577          1
97   46   11457          0
98   83   10508          0
99   70    8827          0

[100 rows x 3 columns]

In [8]:
df.to_csv("Record.csv", index = 0)


In [9]:
dataset = pd.read_csv("Record.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values


# Splitting dataset between training set and test set

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [12]:
print(x_train)

[[   50 15436]
 [   37  2239]
 [   70  8827]
 [   56 12451]
 [   25 15026]
 [   50 16350]
 [   62 15800]
 [   26 12114]
 [   34  7728]
 [   22 11119]
 [   57  6695]
 [   79 10615]
 [   33  4981]
 [   57 15229]
 [   38  9158]
 [   46 11758]
 [   62 18659]
 [   34 11818]
 [   24 17567]
 [   20  6701]
 [   76 14938]
 [   84 10994]
 [   45  5620]
 [   70 19567]
 [   43 12228]
 [   86 16623]
 [   68 19891]
 [   76 19322]
 [   56  5245]
 [   60  5533]
 [   21  4619]
 [   47  7798]
 [   50  5113]
 [   77 15064]
 [   30 16013]
 [   57 17148]
 [   25  3988]
 [   54  4414]
 [   91 12330]
 [   64 16193]
 [   71 19799]
 [   68  5378]
 [   56  9473]
 [   84 13340]
 [   55 12718]
 [   79  5257]
 [   34 10781]
 [   40  3761]
 [   46 11457]
 [   83 10508]
 [   47  4687]
 [   72 16608]
 [   50  7526]
 [   90  3390]
 [   77  3184]
 [   63  8330]
 [   23  5365]
 [   51 17527]
 [   34 11305]
 [   21 12466]
 [   80 15278]
 [   34 19263]
 [   55 18143]
 [   30 14493]
 [   85 11527]
 [   83 19080]
 [   47 13

In [13]:
x_test

array([[   74, 17462],
       [   87,  6801],
       [   87,  6073],
       [   85,  7916],
       [   33,  8510],
       [   69, 10964],
       [   26,  8801],
       [   88, 15524],
       [   79,  3597],
       [   57, 16324],
       [   34,  5680],
       [   52,  6054],
       [   36, 12516],
       [   68, 18410],
       [   79,  2311],
       [   87,  2174],
       [   19, 10748],
       [   94,  4748],
       [   29,  8461],
       [   85,  6898],
       [   33,  4867],
       [   78, 11001],
       [   77, 10697],
       [   18,  3532],
       [   82,  9992]], dtype=int64)

In [14]:
y_train

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [15]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

# Feature scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
print(x_train)

[[-0.17251116  0.74235058]
 [-0.82444287 -1.91380863]
 [ 0.8304607  -0.58784236]
 [ 0.1283804   0.14155985]
 [-1.42622599  0.65982991]
 [-0.17251116  0.92631129]
 [ 0.42927196  0.81561283]
 [-1.3760774   0.07373188]
 [-0.97488865 -0.80903801]
 [-1.57667177 -0.12653169]
 [ 0.17852899 -1.01694984]
 [ 1.28179804 -0.22797174]
 [-1.02503724 -1.3619265 ]
 [ 0.17852899  0.7006877 ]
 [-0.77429428 -0.52122202]
 [-0.37310553  0.00207979]
 [ 0.42927196  1.39104355]
 [-0.97488865  0.01415598]
 [-1.47637458  1.17125679]
 [-1.67696895 -1.01574223]
 [ 1.13135226  0.64211815]
 [ 1.53254101 -0.15169043]
 [-0.42325413 -1.23331502]
 [ 0.8304607   1.57379664]
 [-0.52355131  0.09667665]
 [ 1.63283819  0.98125798]
 [ 0.73016352  1.6390081 ]
 [ 1.13135226  1.52448551]
 [ 0.1283804  -1.30879124]
 [ 0.32897477 -1.2508255 ]
 [-1.62682036 -1.43478621]
 [-0.32295694 -0.79494912]
 [-0.17251116 -1.33535887]
 [ 1.18150085  0.66747816]
 [-1.17548302  0.85848332]
 [ 0.17852899  1.08692469]
 [-1.42622599 -1.56178753]
 

In [18]:
print(x_test)

[[ 1.03105507  1.15012345]
 [ 1.68298678 -0.99561523]
 [ 1.68298678 -1.14213974]
 [ 1.5826896  -0.77119927]
 [-1.02503724 -0.65164493]
 [ 0.78031211 -0.15772853]
 [-1.3760774  -0.59307538]
 [ 1.73313538  0.76006233]
 [ 1.28179804 -1.64048407]
 [ 0.17852899  0.92107827]
 [-0.97488865 -1.22123882]
 [-0.07221397 -1.14596387]
 [-0.87459146  0.15464239]
 [ 0.73016352  1.34092734]
 [ 1.28179804 -1.8993172 ]
 [ 1.68298678 -1.92689118]
 [-1.72711755 -0.20120284]
 [ 2.03402694 -1.40882239]
 [-1.22563162 -0.66150716]
 [ 1.5826896  -0.97609205]
 [-1.02503724 -1.38487127]
 [ 1.23164945 -0.15028154]
 [ 1.18150085 -0.2114676 ]
 [-1.77726614 -1.65356662]
 [ 1.43224382 -0.3533629 ]]


# Training logistic reg. on training dataset 

In [19]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

# Predicting test results

In [20]:
x_test

array([[ 1.03105507,  1.15012345],
       [ 1.68298678, -0.99561523],
       [ 1.68298678, -1.14213974],
       [ 1.5826896 , -0.77119927],
       [-1.02503724, -0.65164493],
       [ 0.78031211, -0.15772853],
       [-1.3760774 , -0.59307538],
       [ 1.73313538,  0.76006233],
       [ 1.28179804, -1.64048407],
       [ 0.17852899,  0.92107827],
       [-0.97488865, -1.22123882],
       [-0.07221397, -1.14596387],
       [-0.87459146,  0.15464239],
       [ 0.73016352,  1.34092734],
       [ 1.28179804, -1.8993172 ],
       [ 1.68298678, -1.92689118],
       [-1.72711755, -0.20120284],
       [ 2.03402694, -1.40882239],
       [-1.22563162, -0.66150716],
       [ 1.5826896 , -0.97609205],
       [-1.02503724, -1.38487127],
       [ 1.23164945, -0.15028154],
       [ 1.18150085, -0.2114676 ],
       [-1.77726614, -1.65356662],
       [ 1.43224382, -0.3533629 ]])

In [21]:
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_pred.shape)
print(y_pred.reshape(len(y_pred),1))
print('predict actual')
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
(25,)
[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
predict actual
[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


# Making confusion matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[21  0]
 [ 0  4]]


1.0